spring.application.name=TaskTracker
spring.datasource.url=jdbc:postgresql://localhost:5432/tasktracker
spring.datasource.username=postgres
spring.datasource.password=pyawesome31
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
jwt.lifetime=86400000
jwt.secret=eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcxNzI1NTc4MCwiaWF0IjoxNzE3MjU1NzgwfQ.b1elaZbHLl2a1h6ynNi5AdsrnuvN0rfRBg1-csfH1nM